# Netlify configuration for Single Page Application
[build]
  publish = "dist"
  command = "npm run build"
  base = "/"

[build.environment]
  NODE_VERSION = "20"

# Security headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"